name: jadwal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.1.0
  intl: ^0.19.0  
  vibration: ^2.0.1
  device_info_plus: ^11.1.0
  image_picker: ^1.1.2 
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/nama.png
    - assets/pp.png
    - assets/buku.png

  fonts:
    - family: Bayon
      fonts:
        - asset: assets/fonts/Bayon-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf     # Pastikan format asset benar 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pp.png"  # Path ke gambar ikon Anda   